### ISSUE TITLE
The link to ask questions leads to a non existing page.

### ISSUE THREAD

**Issue by ACH1980** [wybert/georouting#5]
As mentioned above. It's more a repo-related bug. So where should we ask questions?

![image](https://user-images.githubusercontent.com/39656381/228064761-29d11087-ea08-4b90-9d45-58f96ae0a6cf.png)
![image](https://user-images.githubusercontent.com/39656381/228064790-ecadfe6c-dcb1-4475-b421-4b3142a506c1.png)

**Comment by wybert** [comment]
@ACH1980 it should now work, you can try here, [https://github.com/wybert/georouting/discussions/categories/q-a](https://github.com/wybert/georouting/discussions/categories/q-a)

**Comment by ACH1980** [comment]
I will try at home. Currently on bike tour for the next week or so 🫣

**Comment by wybert** [comment]
> I will try at home. Currently on bike tour for the next week or so 🫣

Wow. Have a good trip! 🚴🏻

**Comment by ACH1980** [comment]
It works 👍
